source("setUp.R")
Sys.setlocale("LC_TIME", "English")
setup()
data <- readData()
data$DateTime <- strptime(paste(as.character(as.Date(data$Date, "%d/%m/%Y")), data$Time), "%Y-%m-%d %H:%M:%S")
png(filename="plot3.png", width=480, height=480, units="px")
with(data, plot(DateTime, SubMetering1, main = "", ylab = "Energy sub metering", type = "l", xlab = ""))
with(data, lines(DateTime, SubMetering2, col = "red"))
with(data, lines(DateTime, SubMetering3, col = "blue"))
legend("topright", c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col = c('black','red','blue'), lwd = 1)
dev.off()